# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Hospital'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.Hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin',
            name='Hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.Hospital'),
        ),
        migrations.AddField(
            model_name='admin',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
