# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 00:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Number_Of_Patients', models.IntegerField(default=0)),
                ('Average_Length_Of_Stay', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Of_Issue', models.DateTimeField(default=django.utils.timezone.now)),
                ('Drug_Name', models.CharField(default='', max_length=40)),
                ('Drug_Strength', models.CharField(default='', max_length=6)),
                ('Dosage_Form', models.CharField(default='', max_length=20)),
                ('Quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1')])),
                ('Number_Of_Refills', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Refills must be at least 0')])),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('Weight', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\d{1,3}', message='Weight must contain digits')])),
                ('Height_Feet', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9, message='Feet must not exceed 9 ft'), django.core.validators.MinValueValidator(0, message='Feet must not be less than 0 ft')])),
                ('Height_Inches', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11, message='Inches must not exceed 11 in'), django.core.validators.MinValueValidator(0, message='Inches must not be less than 0 in')])),
                ('Insurance_ID', models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator('\\d{12}', message='ID must be 12 digits')])),
                ('Admitted', models.BooleanField(default=False)),
                ('Time_Of_Admission', models.DateTimeField(blank=True, null=True)),
                ('Time_Of_Discharge', models.DateTimeField(blank=True, null=True)),
                ('Current_Hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Hospital')),
                ('Patient_Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Record', to='accounts.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Name', models.CharField(max_length=100)),
                ('Notes', models.TextField(blank=True, max_length=500)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Released', models.BooleanField(default=False)),
                ('Files', models.FileField(blank=True, null=True, upload_to='')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tests', to='accounts.Doctor')),
                ('Patient_Record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tests', to='records.Record')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='Patient_Record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prescriptions', to='records.Record'),
        ),
    ]
